[package]
name = "server"
version = "0.2.2"
edition = "2018"

[dependencies]

tokio = { version = "1.9.*", features = ["full"] }
rsa = { version = "0.5.0", features = ["serde"] }
sha2 = "0.9.8"
serde = { version = "1.0.130", features = ["derive"] }
bincode = "1.0.130"